// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Fumon.Gas")>]
[<assembly: AssemblyProductAttribute("Fumon")>]
[<assembly: AssemblyVersionAttribute("0.2.0")>]
[<assembly: AssemblyFileVersionAttribute("0.2.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Fumon.Gas"
    let [<Literal>] AssemblyProduct = "Fumon"
    let [<Literal>] AssemblyVersion = "0.2.0"
    let [<Literal>] AssemblyFileVersion = "0.2.0"
