// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Tsugihagi.Core")>]
[<assembly: AssemblyProductAttribute("Tsugihagi")>]
[<assembly: AssemblyVersionAttribute("0.4.0")>]
[<assembly: AssemblyFileVersionAttribute("0.4.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Tsugihagi.Core"
    let [<Literal>] AssemblyProduct = "Tsugihagi"
    let [<Literal>] AssemblyVersion = "0.4.0"
    let [<Literal>] AssemblyFileVersion = "0.4.0"
